### ISSUE TITLE
Add commit message to default description

### ISSUE THREAD

**Issue by inwardmovement** [rjstone/discord-webhook-notify#1]
Hi, your action is awesomely working!

Could you add the "commit message" (the commit message from the commit triggering the workflow) field in the default description?

**Comment by rjstone** [comment]
I think I tried to do that but it was not in the webhook data or something. Let me dig around and see if I can find a way to make that work. I'm pretty sure it's in there somewhere, I was probably just looking in the wrong place.

**Comment by rjstone** [comment]
Done in version v1.0.2

Use @v1 or @v1.0.2 to get the update. (You'll get it automatically if you were already using @v1)

If you have any enhancements you want to make yourself, feel free to send pull requests.

**Comment by inwardmovement** [comment]
Thank you!
